### ISSUE TITLE
ChestTerminal failing to enable.

### ISSUE THREAD

**Issue by MagmaBro123** [TheBusyBiscuit/ChestTerminal#50] opened 2021-01-25 00:06 UTC
## Description (Required)
The plugin fails to load. This is probably due to the CS-CoreLib Removal change.

## Steps to reproduce the Issue (Required)
Use the plugin.

## Expected behavior (Required)
Plugin enabling without erroring.

## Server Log / Error Report
https://pastebin.com/MNNn3LJK

## Environment (Required)
![2021-01-24_16 05 50](https://user-images.githubusercontent.com/51277766/105648020-10fec180-5e5e-11eb-92aa-02c365f1c711.png)
![2021-01-24_16 05 55](https://user-images.githubusercontent.com/51277766/105648021-122fee80-5e5e-11eb-9e9f-4f16158b6d30.png)

**Comment by TheBusyBiscuit** [comment] 2021-01-25 00:07
Duplicate of #49

**Comment by MagmaBro123** [comment] 2021-01-25 00:07
I gave you info...

**Closed by TheBusyBiscuit** 2021-01-25 00:07 UTC
Labels: Bug Report
